steps:
  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args: ["version"]
    env: ["GOPATH=."]

  - id: go_run
    name: "gcr.io/cloud-builders/go"
    args: ["run","neopoeple-gcp"]
    env: ["GOPATH=."]